version: '3.1'
networks:
  banco:
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: itix
      POSTGRES_PASSWORD: itix123
      POSTGRES_DB: itixdb
    volumes: 
      - /etc/postgresql
      - /var/log/postgresql
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      banco:
        ipv4_address: 192.168.1.2
