CREATE TABLE endereco(
	ID_ENDERECO SERIAL PRIMARY KEY,
	LOGRADOURO VARCHAR NOT NULL,
	NUMERO INT NOT NULL,
	BAIRO VARCHAR NOT NULL,
	CIDADE VARCHAR NOT NULL,
	CEP VARCHAR NOT NULL,
	UL VARCHAR NOT NULL,
	COMPLEMENTO VARCHAR NULL
);
/*criado*/

INSERT INTO ENDERECO (LOGRADOURO,NUMERO ,BAIRO ,CIDADE, CEP, UL, COMPLEMENTO )
VALUES ('RUA PADRE ANCHIETA',135, 'CENTRO', 'ALEGRE', 29500000, 'ES', 'EM CIMA DA CLINICA VIVARE');

INSERT INTO ENDERECO (LOGRADOURO,NUMERO ,BAIRO ,CIDADE, CEP, UL, COMPLEMENTO )
VALUES ('AV OLIVIO CORREA PEDROSA', 1000, 'CENTRO', 'ALEGRE', 29500000, 'ES', 'EM FRENTE AO SAAE');

INSERT INTO ENDERECO (LOGRADOURO,NUMERO ,BAIRO ,CIDADE, CEP, UL, COMPLEMENTO )
VALUES ('RUA VITÓRIO ALBANIS', 1000, 'CENTRO', 'ALEGRE', 29500000, 'ES', 'EM FRENTE AO SAAE');

select * from endereco ;
