SELECT C.*, CE.*, DEP.NM_DEPARTAMENTO, CDP.*, CF.*, CH.*, CC.*, CDB.* , CFE.*, TE.NM_TIPO_EQUIPAMENTO ,TE.NM_FABRICANTE 
FROM COLABORADOR C
LEFT JOIN COLABORADOR_ENDERECO CE ON C.ID_COLABORADOR = CE.ID_COLABORADOR
LEFT JOIN COLABORADOR_EQUIPAMENTO CEQ ON C.ID_COLABORADOR = CEQ.ID_COLABORADOR
LEFT JOIN COLABORADOR_DEPARTAMENTO CD ON C.ID_COLABORADOR = CD.ID_COLABORADOR
LEFT JOIN COLABORADOR_DEPENDENTE CDP ON C.ID_COLABORADOR = CDP.ID_COLABORADOR
LEFT JOIN COLABORADOR_FORMACAO CF ON C.ID_COLABORADOR = CF.ID_COLABORADOR
LEFT JOIN COLABORADOR_HOLERITE CH ON C.ID_COLABORADOR = CH.ID_COLABORADOR
LEFT JOIN COLABORADOR_CONTATO CC ON C.ID_COLABORADOR = CC.ID_COLABORADOR
LEFT JOIN COLABORADOR_DADO_BANCARIO CDB ON C.ID_COLABORADOR = CDB.ID_COLABORADOR
LEFT JOIN COLABORADOR_FERIAS CFE ON C.ID_COLABORADOR = CFE.ID_COLABORADOR
LEFT JOIN DEPARTAMENTO DEP ON DEP.ID_DEPARTAMENTO = CD.ID_DEPARTAMENTO
LEFT JOIN TIPO_EQUIPAMENTO TE ON CEQ.ID_EQUIPAMENTO = TE.ID_TIPO_EQUIPAMENTO;