INSERT INTO TIPO_CONTRATO(NM_TIPO_CONTRATO) VALUES ('Pessoa Fisica - CLT');
INSERT INTO TIPO_CONTRATO(NM_TIPO_CONTRATO) VALUES ('Pessoa Juridica');
INSERT INTO TIPO_CONTRATO(NM_TIPO_CONTRATO) VALUES ('Estagio');
COMMIT;

INSERT INTO TIPO_TICKET(NM_TIPO_TICKET) VALUES ('Alimentacao');
INSERT INTO TIPO_TICKET(NM_TIPO_TICKET) VALUES ('Refeicao');
COMMIT;

INSERT INTO CARGO(NM_CARGO) VALUES('Estagiario');
INSERT INTO CARGO(NM_CARGO) VALUES('Analista Desenvolvedor');
INSERT INTO CARGO(NM_CARGO) VALUES('Analista de Qualidade');
INSERT INTO CARGO(NM_CARGO) VALUES('Scrum Master');
INSERT INTO CARGO(NM_CARGO) VALUES('Gerente de Projetos');
INSERT INTO CARGO(NM_CARGO) VALUES('Recursos Humanos');
INSERT INTO CARGO(NM_CARGO) VALUES('Analista Administrativo');
COMMIT;


INSERT INTO COLABORADOR(NM_COLABORADOR,CD_CPF_CNPJ,DT_ADMISSAO,VL_SALARIO,ID_CARGO,ID_TIPO_CONTRATO,ID_TICKET,DT_NASCIMENTO,CD_UF_NATURAL,CD_ETINIA,NM_CIDADE_NATURAL,CD_GENERO,CD_ESTADO_CIVIL,NM_MAE,NM_PAI,FL_CADASTRO_COMPLETO)
VALUES ('Luan Sérgio Enrico da Rosa','26130953690','2021-03-29',1000,2,1,1,'1973-04-01','ES',1,'Alegre',1,1,'Antonella Rafaela Isis','Mateus Diego Otavio da Rosa',false);
INSERT INTO COLABORADOR(NM_COLABORADOR,CD_CPF_CNPJ,DT_ADMISSAO,VL_SALARIO,ID_CARGO,ID_TIPO_CONTRATO,ID_TICKET,DT_NASCIMENTO,CD_UF_NATURAL,CD_ETINIA,NM_CIDADE_NATURAL,CD_GENERO,CD_ESTADO_CIVIL,NM_MAE,NM_PAI,FL_CADASTRO_COMPLETO)
VALUES ('Olivia Carla Tânia da Cunha','09617670810','2021-03-29',600,1,3,2,'2002-02-10','ES',2,'Vitoria',2,1,'Elza Jessica Sara','Caio Eduardo Calebe da Cunha',true);
INSERT INTO COLABORADOR(NM_COLABORADOR,CD_CPF_CNPJ,DT_ADMISSAO,VL_SALARIO,ID_CARGO,ID_TIPO_CONTRATO,ID_TICKET,DT_NASCIMENTO,CD_UF_NATURAL,CD_ETINIA,NM_CIDADE_NATURAL,CD_GENERO,CD_ESTADO_CIVIL,NM_MAE,NM_PAI,FL_CADASTRO_COMPLETO)
VALUES ('Pietro Osvaldo Rocha','17741418769','2014-04-05',10000,4,2,1,'1961-03-29','ES',2,'Vitoria',1,1,'Elza Jessica Sara','Caio Eduardo Calebe da Cunha',true);
INSERT INTO COLABORADOR(NM_COLABORADOR,CD_CPF_CNPJ,DT_ADMISSAO,VL_SALARIO,ID_CARGO,ID_TIPO_CONTRATO,ID_TICKET,DT_NASCIMENTO,CD_UF_NATURAL,CD_ETINIA,NM_CIDADE_NATURAL,CD_GENERO,CD_ESTADO_CIVIL,NM_MAE,NM_PAI,FL_CADASTRO_COMPLETO)
VALUES ('Beatriz Juliana Lorena Corte Real','14790688291','2014-04-05',10000,5,2,1,'1985-10-15','ES',4,'Vitoria',2,1,'Elza Jessica Sara','Caio Eduardo Calebe da Cunha',true);
INSERT INTO COLABORADOR(NM_COLABORADOR,CD_CPF_CNPJ,DT_ADMISSAO,VL_SALARIO,ID_CARGO,ID_TIPO_CONTRATO,ID_TICKET,DT_NASCIMENTO,CD_UF_NATURAL,CD_ETINIA,NM_CIDADE_NATURAL,CD_GENERO,CD_ESTADO_CIVIL,NM_MAE,NM_PAI,FL_CADASTRO_COMPLETO)
VALUES ('Gabriela Sarah Simone da Silva','89410024781','2014-04-05',5000,3,1,2,'1987-03-29','ES',2,'Vitoria',2,1,'Elza Jessica Sara','Caio Eduardo Calebe da Cunha',true);
COMMIT;


INSERT INTO	COLABORADOR_ENDERECO( ID_COLABORADOR, NM_LUGRADOURO, CD_NUMERO, NM_BAIRRO, NM_CIDADE, CD_CEP, NM_UF )
VALUES ( 1, 'Rua Padre Caldas', 269, 'Partenon', 'Porto Alegre', '90620280', 'RS' );
INSERT INTO	COLABORADOR_ENDERECO( ID_COLABORADOR, NM_LUGRADOURO, CD_NUMERO, NM_BAIRRO, NM_CIDADE, CD_CEP, NM_UF, TX_COMPLEMENTO)
VALUES ( 2, 'Rua Corypheu de Azevedo Marques', 433, 'Vila Santo Antonio', 'Maringa', '87030250', 'PR', 'Ao lado de alguma coisa');
INSERT INTO	COLABORADOR_ENDERECO( ID_COLABORADOR, NM_LUGRADOURO, CD_NUMERO, NM_BAIRRO, NM_CIDADE, CD_CEP, NM_UF, TX_COMPLEMENTO)
VALUES ( 3, 'Rua Ercilia Maria de Souza', 704, 'Brasilia', 'Arapiraca', '57313735', 'AL', 'Ao lado de alguma coisa');
INSERT INTO	COLABORADOR_ENDERECO( ID_COLABORADOR, NM_LUGRADOURO, CD_NUMERO, NM_BAIRRO, NM_CIDADE, CD_CEP, NM_UF, TX_COMPLEMENTO)
VALUES ( 4, 'Rua Rio Tocantins', 247, 'Fazendinha', 'Macapa', '68911046', 'AP', 'Ao lado de alguma coisa');
INSERT INTO	COLABORADOR_ENDERECO( ID_COLABORADOR, NM_LUGRADOURO, CD_NUMERO, NM_BAIRRO, NM_CIDADE, CD_CEP, NM_UF, TX_COMPLEMENTO)
VALUES ( 5, 'Rua Domingos Meirelles', 336, 'Santa Sofia', 'Americana', '13477231', 'SP', 'Ao lado de alguma coisa');
COMMIT;

INSERT INTO	COLABORADOR_CONTATO( ID_COLABORADOR, TX_EMAIL, CD_CELULAR, CD_RESIDENCIAL, NM_CONTATO_EMERGENCIA )
VALUES ( 1, 'email@email.com.br', '28999999999', NULL, NULL );
INSERT INTO	COLABORADOR_CONTATO( ID_COLABORADOR, TX_EMAIL, CD_CELULAR, CD_RESIDENCIAL, NM_CONTATO_EMERGENCIA )
VALUES ( 2, 'email@email.com.br', '28999999999', NULL, NULL );
INSERT INTO	COLABORADOR_CONTATO( ID_COLABORADOR, TX_EMAIL, CD_CELULAR, CD_RESIDENCIAL, NM_CONTATO_EMERGENCIA )
VALUES ( 3, 'email@email.com.br', '28999999999', NULL, NULL );
INSERT INTO	COLABORADOR_CONTATO( ID_COLABORADOR, TX_EMAIL, CD_CELULAR, CD_RESIDENCIAL, NM_CONTATO_EMERGENCIA )
VALUES ( 3, 'email@email.com.br', '28999999999', NULL, 'Elza Jessica Sara' );
INSERT INTO	COLABORADOR_CONTATO( ID_COLABORADOR, TX_EMAIL, CD_CELULAR, CD_RESIDENCIAL, NM_CONTATO_EMERGENCIA )
VALUES ( 4, 'email@email.com.br', '28999999999', NULL, NULL);
INSERT INTO	COLABORADOR_CONTATO( ID_COLABORADOR, TX_EMAIL, CD_CELULAR, CD_RESIDENCIAL, NM_CONTATO_EMERGENCIA )
VALUES ( 5, 'email@email.com.br', '28999999999', NULL, NULL );
COMMIT;

INSERT INTO COLABORADOR_DADO_BANCARIO( ID_COLABORADOR, NM_BANCO, CD_AGENCIA, CD_CONTA, DS_TIPO_CONTA )
VALUES ( 1, 'Nu Pagamentos S.A.', '0345', '1234564', 'Corrente' );
INSERT INTO COLABORADOR_DADO_BANCARIO( ID_COLABORADOR, NM_BANCO, CD_AGENCIA, CD_CONTA, DS_TIPO_CONTA )
VALUES ( 2, 'Caixa Economica Federal', '0542', '1234567', 'Poupanca' );
INSERT INTO COLABORADOR_DADO_BANCARIO( ID_COLABORADOR, NM_BANCO, CD_AGENCIA, CD_CONTA, DS_TIPO_CONTA )
VALUES ( 3, 'Banco do Brasil', '1547', '4257861', 'Corrente' );
INSERT INTO COLABORADOR_DADO_BANCARIO( ID_COLABORADOR, NM_BANCO, CD_AGENCIA, CD_CONTA, DS_TIPO_CONTA )
VALUES ( 4, 'Santander', '3663', '9543287', 'Corrente' );
INSERT INTO COLABORADOR_DADO_BANCARIO( ID_COLABORADOR, NM_BANCO, CD_AGENCIA, CD_CONTA, DS_TIPO_CONTA )
VALUES ( 5, 'Itau', '4785', '9647812', 'Corrente' );
COMMIT;

INSERT INTO DEPARTAMENTO(NM_DEPARTAMENTO, ID_GESTOR)
VALUES('Desenvolvimento', 1);
INSERT INTO DEPARTAMENTO(NM_DEPARTAMENTO, ID_GESTOR)
VALUES('Vendas', 2);

INSERT INTO COLABORADOR_DEPARTAMENTO(ID_DEPARTAMENTO, ID_COLABORADOR)
VALUES(1, 1);
INSERT INTO COLABORADOR_DEPARTAMENTO(ID_DEPARTAMENTO, ID_COLABORADOR)
VALUES(2, 2);
INSERT INTO COLABORADOR_DEPARTAMENTO(ID_DEPARTAMENTO, ID_COLABORADOR)
VALUES(1, 3);
INSERT INTO COLABORADOR_DEPARTAMENTO(ID_DEPARTAMENTO, ID_COLABORADOR)
VALUES(1, 4);
INSERT INTO COLABORADOR_DEPARTAMENTO(ID_DEPARTAMENTO, ID_COLABORADOR)
VALUES(2, 5);

INSERT INTO ESCOLARIDADE(DS_ESCOLARIDADE)
VALUES('Ensino fundamental completo');
INSERT INTO ESCOLARIDADE(DS_ESCOLARIDADE)
VALUES('Ensino fundamental incompleto');
INSERT INTO ESCOLARIDADE(DS_ESCOLARIDADE)
VALUES('Ensino médio completo');
INSERT INTO ESCOLARIDADE(DS_ESCOLARIDADE)
VALUES('Ensino médio incompleto');
INSERT INTO ESCOLARIDADE(DS_ESCOLARIDADE)
VALUES('Ensino superior completo');
INSERT INTO ESCOLARIDADE(DS_ESCOLARIDADE)
VALUES('Ensino superior incompleto');
INSERT INTO ESCOLARIDADE(DS_ESCOLARIDADE)
VALUES('Pós graduação completo');
INSERT INTO ESCOLARIDADE(DS_ESCOLARIDADE)
VALUES('Pós graduação incompleto');
INSERT INTO ESCOLARIDADE(DS_ESCOLARIDADE)
VALUES('Doutorado completo');
INSERT INTO ESCOLARIDADE(DS_ESCOLARIDADE)
VALUES('Doutorado incompleto');

INSERT INTO COLABORADOR_FORMACAO(ID_COLABORADOR, ID_ESCOLARIDADE, NM_INSTITUICAO, NM_CURSO, DT_ANO_CONCLUSAO      
VALUES(1, 6, 'UFES', 'Ciência da Computação', '2021-02-20');
INSERT INTO COLABORADOR_FORMACAO(ID_COLABORADOR, ID_ESCOLARIDADE, NM_INSTITUICAO, NM_CURSO, DT_ANO_CONCLUSAO      
VALUES(2, 5, 'UFES', 'Sistemas de informação', '2020-02-20');
INSERT INTO COLABORADOR_FORMACAO(ID_COLABORADOR, ID_ESCOLARIDADE, NM_INSTITUICAO, NM_CURSO, DT_ANO_CONCLUSAO      
VALUES(3, 5, 'UFES', 'Ciência da Computação', '2020-02-20');
INSERT INTO COLABORADOR_FORMACAO(ID_COLABORADOR, ID_ESCOLARIDADE, NM_INSTITUICAO, NM_CURSO, DT_ANO_CONCLUSAO      
VALUES(4, 5, 'UFES', 'Ciência da Computação', '2020-02-20');
INSERT INTO COLABORADOR_FORMACAO(ID_COLABORADOR, ID_ESCOLARIDADE, NM_INSTITUICAO, NM_CURSO, DT_ANO_CONCLUSAO      
VALUES(5, 6, 'UFES', 'Sistemas de informação', '2020-02-20');

INSERT INTO COLABORADOR_DEPENDENTE(ID_COLABORADOR, NM_DEPENDETE, CD_CPF, DT_NASCIMENTO, TX_EMAIL, DS_RELACAO_PARENTAL)
VALUES(1, 'Ronaldo', '13478945632', '2000-02-10', 'ronaldo@hotmail.com', 'filho');
INSERT INTO COLABORADOR_DEPENDENTE(ID_COLABORADOR, NM_DEPENDETE, CD_CPF, DT_NASCIMENTO, TX_EMAIL, DS_RELACAO_PARENTAL)
VALUES(2, 'Pelé', '13478945832', '20010-02-10', 'pele@hotmail.com', 'pai');

INSERT INTO TIPO_EQUIPAMENTO(NM_TIPO_EQUIPAMENTO, NM_FABRICANTE)
VALUES('Mouse gamer', 'Logitec');
INSERT INTO TIPO_EQUIPAMENTO(NM_TIPO_EQUIPAMENTO, NM_FABRICANTE)
VALUES('Teclado gamer', 'Logitec');
INSERT INTO TIPO_EQUIPAMENTO(NM_TIPO_EQUIPAMENTO, NM_FABRICANTE)
VALUES('Headset gamer', 'Razer');
INSERT INTO TIPO_EQUIPAMENTO(NM_TIPO_EQUIPAMENTO, NM_FABRICANTE)
VALUES('Notebook gamer', 'Dell');



INSERT INTO EQUIPAMENTO(ID_TIPO_EQUIPAMENTO, DT_AQUISICAO)
VALUES(1, '2021-03-29');
INSERT INTO EQUIPAMENTO(ID_TIPO_EQUIPAMENTO, DT_AQUISICAO)
VALUES(2, '2021-03-29');
INSERT INTO EQUIPAMENTO(ID_TIPO_EQUIPAMENTO, DT_AQUISICAO)
VALUES(3, '2021-03-29');
INSERT INTO EQUIPAMENTO(ID_TIPO_EQUIPAMENTO, DT_AQUISICAO)
VALUES(4, '2021-03-30');

INSERT INTO COLABORADOR_EQUIPAMENTO(ID_COLABORADOR, ID_EQUIPAMENTO, DT_ATRIBUICAO)
VALUES(1, 1, '2021-03-29');
INSERT INTO COLABORADOR_EQUIPAMENTO(ID_COLABORADOR, ID_EQUIPAMENTO, DT_ATRIBUICAO)
VALUES(2, 1, '2021-03-29');
INSERT INTO COLABORADOR_EQUIPAMENTO(ID_COLABORADOR, ID_EQUIPAMENTO, DT_ATRIBUICAO)
VALUES(3, 1, '2021-03-29');
INSERT INTO COLABORADOR_EQUIPAMENTO(ID_COLABORADOR, ID_EQUIPAMENTO, DT_ATRIBUICAO)
VALUES(1, 2, '2021-03-29');
INSERT INTO COLABORADOR_EQUIPAMENTO(ID_COLABORADOR, ID_EQUIPAMENTO, DT_ATRIBUICAO)
VALUES(2, 2, '2021-03-29');
INSERT INTO COLABORADOR_EQUIPAMENTO(ID_COLABORADOR, ID_EQUIPAMENTO, DT_ATRIBUICAO)
VALUES(3, 2, '2021-03-29');
INSERT INTO COLABORADOR_EQUIPAMENTO(ID_COLABORADOR, ID_EQUIPAMENTO, DT_ATRIBUICAO)
VALUES(1, 3, '2021-03-29');
INSERT INTO COLABORADOR_EQUIPAMENTO(ID_COLABORADOR, ID_EQUIPAMENTO, DT_ATRIBUICAO)
VALUES(2, 3, '2021-03-29');
INSERT INTO COLABORADOR_EQUIPAMENTO(ID_COLABORADOR, ID_EQUIPAMENTO, DT_ATRIBUICAO)
VALUES(1, 4, '2021-03-29');
INSERT INTO COLABORADOR_EQUIPAMENTO(ID_COLABORADOR, ID_EQUIPAMENTO, DT_ATRIBUICAO)
VALUES(2, 4, '2021-03-29');
INSERT INTO COLABORADOR_EQUIPAMENTO(ID_COLABORADOR, ID_EQUIPAMENTO, DT_ATRIBUICAO)
VALUES(4, 4, '2021-03-30');

INSERT INTO COLABORADOR_FERIAS(ID_COLABORADOR, DT_SOLICITACAO, DT_INICIO, DT_FIM, QT_DIAS_ABONO , FL_ANTECIPAR_DECIMO_TERCEIRO, TX_JUSTIFICATIVA)
VALUES(1, '2021-03-28', '2021-03-29', '2021-04-29', 5, 'true', 'estresse'); 
INSERT INTO COLABORADOR_FERIAS(ID_COLABORADOR, DT_SOLICITACAO, DT_INICIO, DT_FIM, QT_DIAS_ABONO , FL_ANTECIPAR_DECIMO_TERCEIRO, TX_JUSTIFICATIVA)
VALUES(3, '2021-03-28', '2021-03-29', '2021-04-29', 5, 'true', 'estresse'); 
INSERT INTO COLABORADOR_FERIAS(ID_COLABORADOR, DT_SOLICITACAO, DT_INICIO, DT_FIM, QT_DIAS_ABONO , FL_ANTECIPAR_DECIMO_TERCEIRO, TX_JUSTIFICATIVA)
VALUES(3, '2020-04-30', '2021-03-28', '2021-04-29', 5, 'true', 'estresse'); 
INSERT INTO COLABORADOR_FERIAS(ID_COLABORADOR, DT_SOLICITACAO, DT_INICIO, DT_FIM, DT_APROVACAO, QT_DIAS_ABONO , FL_ANTECIPAR_DECIMO_TERCEIRO, TX_JUSTIFICATIVA)
VALUES(3, '2020-04-30', '2021-03-28', '2021-04-29', '2021-03-30', 5, 'true', 'estresse'); 


INSERT INTO TIPO_HOLERITE(NM_HOLERITE)
VALUES('Mensal');
INSERT INTO TIPO_HOLERITE(NM_HOLERITE)
VALUES('Anual');
INSERT INTO TIPO_HOLERITE(NM_HOLERITE)
VALUES('Diária');
INSERT INTO TIPO_HOLERITE(NM_HOLERITE)
VALUES('PRIMEIRA PARCELA');
INSERT INTO TIPO_HOLERITE(NM_HOLERITE)
VALUES('SEGUNDA PARCELA');
INSERT INTO TIPO_HOLERITE(NM_HOLERITE)
VALUES('TERCEIRA PARCELA');

INSERT INTO COLABORADOR_HOLERITE(ID_COLABORADOR, ID_TIPO_HOLERITE, DT_REFERENCIA, VL_DESCONTO, VL_VALOR)
VALUES(1, 1, '2020-03-28', 200, 1000);
INSERT INTO COLABORADOR_HOLERITE(ID_COLABORADOR, ID_TIPO_HOLERITE, DT_REFERENCIA, VL_DESCONTO, VL_VALOR)
VALUES(2, 1, '2020-06-28', 200, 2000);
INSERT INTO COLABORADOR_HOLERITE(ID_COLABORADOR, ID_TIPO_HOLERITE, DT_REFERENCIA, VL_DESCONTO, VL_VALOR)
VALUES(3, 3, '2021-03-28', 10, 200);
INSERT INTO COLABORADOR_HOLERITE(ID_COLABORADOR, ID_TIPO_HOLERITE, DT_REFERENCIA, VL_DESCONTO, VL_VALOR)
VALUES(4, 2, '2021-06-28', 500, 9000);
INSERT INTO COLABORADOR_HOLERITE(ID_COLABORADOR, ID_TIPO_HOLERITE, DT_REFERENCIA, VL_DESCONTO, VL_VALOR)
VALUES(4, 3, '2021-12-28', 500, 9000);
INSERT INTO COLABORADOR_HOLERITE(ID_COLABORADOR, ID_TIPO_HOLERITE, DT_REFERENCIA, VL_DESCONTO, VL_VALOR)
VALUES(4, 3, '2021-12-30', 500, 8000);
INSERT INTO COLABORADOR_HOLERITE(ID_COLABORADOR, ID_TIPO_HOLERITE, DT_REFERENCIA, VL_DESCONTO, VL_VALOR)
VALUES(5, 4, '2021-12-30', 500, 8000);