--ID, NM, DS, TX, CD, VL, DT, FL;
	
create table TIPO_CONTRATO(
	ID_TIPO_CONTRATO SERIAL primary key, 
	NM_TIPO_CONTRATO varchar(50) not null unique
);


CREATE TABLE TIPO_TICKET(
    ID_TIPO_TICKET SERIAL primary key,
    NM_TIPO_TICKET varchar(50) not null UNIQUE
);

create table CARGO(
	ID_CARGO SERIAL primary key,
    NM_CARGO varchar(50) not null UNIQUE
);

create table COLABORADOR(
	ID_COLABORADOR SERIAL primary key,
	NM_COLABORADOR VARCHAR(250) not null,
	CD_CPF_CNPJ VARCHAR(14) unique,
	DT_ADMISSAO DATE not null,	
	VL_SALARIO numeric(9,2) not null,
	ID_CARGO INT references CARGO(ID_CARGO),
	ID_TIPO_CONTRATO INT references TIPO_CONTRATO(ID_TIPO_CONTRATO),
	ID_TICKET INT references TIPO_TICKET(ID_TIPO_TICKET),
	DT_NASCIMENTO DATE,
	CD_UF_NATURAL VARCHAR(2),
	CD_ETINIA INT,
	NM_CIDADE_NATURAL VARCHAR(50),
	CD_GENERO INT,
	CD_ESTADO_CIVIL INT,
	NM_MAE VARCHAR(250),
	NM_PAI VARCHAR(250),	
	FL_CADASTRO_COMPLETO BOOLEAN default false
);

comment on column COLABORADOR.CD_ETINIA is '1 = BRANCO, 2 = PRETO, 3 = PARDO, 4 = INDIO, 5 = AMARELO';
comment on column COLABORADOR.CD_GENERO is '1 = MASCULINO, 2 = FEMININO, 3 = OUTRO';
comment on column COLABORADOR.CD_ESTADO_CIVIL is '1 = SOLTEIRO(A), 2 = CASADO(A), 3 = DIVORCIADO(A), 4 = VIUVO(A)';


CREATE TABLE COLABORADOR_ENDERECO(
    ID_COLABORADOR_ENDERECO serial primary key,
    ID_COLABORADOR INT references COLABORADOR(ID_COLABORADOR),
    NM_LUGRADOURO varchar(100) not null,
    CD_NUMERO int not null,
    NM_BAIRRO varchar(100) not null,
    NM_CIDADE VARCHAR(50) not null,
    CD_CEP varchar(8) not null,
    NM_UF char(2) not null,
    TX_COMPLEMENTO varchar(50)    
);

CREATE TABLE COLABORADOR_CONTATO(
    ID_COLABORADOR_CONTATO SERIAL primary key,
    ID_COLABORADOR int REFERENCES COLABORADOR(ID_COLABORADOR),
    TX_EMAIL varchar(100) not null,
    CD_CELULAR varchar(11) not null,
    CD_RESIDENCIAL varchar(10),
    NM_CONTATO_EMERGENCIA varchar(70)
);

CREATE TABLE COLABORADOR_DADO_BANCARIO(
    ID_COLABORADOR_DADO_BANCARIO SERIAL primary key,
    ID_COLABORADOR int REFERENCES COLABORADOR(ID_COLABORADOR),
    NM_BANCO varchar(50) not null,
    CD_AGENCIA varchar(4) not null,
    CD_CONTA varchar(11) not null,
    DS_TIPO_CONTA varchar(50) not null
);

CREATE TABLE DEPARTAMENTO(
    ID_DEPARTAMENTO SERIAL primary key,    
    NM_DEPARTAMENTO varchar(50) not null UNIQUE,
    ID_GESTOR int REFERENCES COLABORADOR(ID_COLABORADOR)
);


CREATE TABLE COLABORADOR_DEPARTAMENTO(
    ID_COLABORADOR_DEPARTAMENTO SERIAL primary key,
    ID_DEPARTAMENTO int REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    ID_COLABORADOR int REFERENCES COLABORADOR(ID_COLABORADOR)
);

create table ESCOLARIDADE(
	ID_ESCOLARIDADE SERIAL primary key,
	DS_ESCOLARIDADE VARCHAR(50) not null UNIQUE
);

CREATE TABLE COLABORADOR_FORMACAO(
    ID_COLABORADOR_FORMACAO SERIAL primary key,
    ID_COLABORADOR int REFERENCES COLABORADOR(ID_COLABORADOR),
    ID_ESCOLARIDADE INT REFERENCES ESCOLARIDADE(ID_ESCOLARIDADE),
    NM_INSTITUICAO varchar(250) not NULL,
    NM_CURSO varchar(50),
    DT_ANO_CONCLUSAO INT     
);

create table COLABORADOR_DEPENDENTE(
	ID_COLABORADOR_DEPENDENTE SERIAL primary key,
	ID_COLABORADOR int REFERENCES COLABORADOR(ID_COLABORADOR),
    NM_DEPENDETE varchar(250) not null,
    CD_CPF varchar(11) not null UNIQUE,
    DT_NASCIMENTO date not null,
    TX_EMAIL varchar(50) not null,    
    DS_RELACAO_PARENTAL VARCHAR(50) not null
);

CREATE TABLE TIPO_EQUIPAMENTO(
    ID_TIPO_EQUIPAMENTO SERIAL primary key,
    NM_TIPO_EQUIPAMENTO varchar(50) not null,
    NM_FABRICANTE varchar(50) not null
);

CREATE TABLE EQUIPAMENTO(
    ID_EQUIPAMENTO SERIAL primary key,
    ID_TIPO_EQUIPAMENTO int REFERENCES TIPO_EQUIPAMENTO(ID_TIPO_EQUIPAMENTO),
    DT_AQUISICAO date not null
);

CREATE TABLE COLABORADOR_EQUIPAMENTO(
    ID_COLABORADOR_EQUIPAMENTO SERIAL not null,
    ID_COLABORADOR int REFERENCES COLABORADOR(ID_COLABORADOR),
    ID_EQUIPAMENTO int REFERENCES EQUIPAMENTO(ID_EQUIPAMENTO),
   	DT_ATRIBUICAO date not null
);

CREATE TABLE COLABORADOR_FERIAS(
    ID_COLABORADOR_FERIAS SERIAL primary key,
    ID_COLABORADOR int REFERENCES COLABORADOR(ID_COLABORADOR),
    DT_SOLICITACAO date not null,     
    DT_INICIO date not null,
    DT_FIM date not null,
    DT_APROVACAO date,
    QT_DIAS_ABONO int default 0,
    FL_ANTECIPAR_DECIMO_TERCEIRO boolean default FALSE,
    TX_JUSTIFICATIVA varchar(250)    
);

CREATE TABLE TIPO_HOLERITE(
    ID_TIPO_HOLERITE SERIAL primary key,
    NM_HOLERITE varchar(50) UNIQUE
);

CREATE TABLE COLABORADOR_HOLERITE(
    ID_COLABORADOR_HOLERITE SERIAL primary key,
    ID_COLABORADOR int REFERENCES COLABORADOR(ID_COLABORADOR),
    ID_TIPO_HOLERITE int REFERENCES TIPO_HOLERITE(ID_TIPO_HOLERITE),
    DT_REFERENCIA date not null,
    VL_DESCONTO numeric(9,2) not null,
    VL_VALOR numeric(9,2) not null 
);

